{{- range $ns := .Values.secret.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $ns }}
  name: {{ $.Values.secret.name | default $.Release.Name }}
  labels:
    {{- include "secret-distributor.labels" $ | nindent 4 }}
    {{- if $.Values.secret.labels }}
    {{- toYaml $.Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if $.Values.secret.annotations }}
  annotations:
    {{- toYaml $.Values.secret.annotations | nindent 4 }}
  {{- end }}
type: {{ $.Values.secret.type | default "Opaque" }}
data:
  {{- range $k, $v := $.Values.secret.data }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
