{{- range $ns := .Values.secret.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $ns }}
  name: {{ $.Values.secret.name | default $.Release.Name }}
  labels:
    {{- include "secret-distributor.labels" $ | nindent 4 }}
    {{- if $.Values.secret.labels }}
    {{- toYaml $.Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if $.Values.secret.annotations }}
  annotations:
    {{- toYaml $.Values.secret.annotations | nindent 4 }}
  {{- end }}
type: {{ $.Values.secret.type | default "Opaque" }}
{{- if $.Values.secret.base64Data }}
data:
  {{- toYaml $.Values.secret.base64Data | nindent 2 }}
{{- end }}
{{- if $.Values.secret.stringData }}
stringData:
  {{- toYaml $.Values.secret.stringData | nindent 2 }}
{{- else if $.Values.secret.data }}
stringData:
  {{- toYaml $.Values.secret.data | nindent 2 }}
{{- end }}
{{- end }}
