{{- range $ns := .Values.secret.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $ns }}
  name: {{ $.Values.secret.name | default $.Release.Name }}
  labels:
    {{- include "secret-distributor.labels" $ | nindent 4 }}
type: opaque
data:
  {{- range $k, $v := $.Values.secret.data }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}