apiVersion: v2
name: secret-distributor
description: A simple chart which only aims to distribute Secret resource, intended to be used with helm-secrets
type: application
version: 0.4.0
appVersion: 1.0.0
